### ISSUE TITLE
Iinvalid plugin, check your sources

### ISSUE THREAD

**Issue by zXTury** [PluginsOCSInventory-NG/listprinters#1]
Hi..!!

When I try to install the plugin I get the following error: listprinters-master is an invalid plugin, check your sources. Installation aborted !

Im using XAMPP 1.7.7 [PHP: 5.3.8] under Windows 7, is there any chance to get this? or i have to install it manually?

**Comment by gillesdubois** [comment]
Hi,

Did you use this link to install the plugin ?
https://github.com/PluginsOCSInventory-NG/listprinters/releases/download/1.0/listprinters.zip

Regards,
Gilles Dubois.

**Comment by zXTury** [comment]
MAN!!! your the best!! now I know what I was doing wrong! thank you so much! =)
