### ISSUE TITLE
Reinstall Plugin

### ISSUE THREAD

**Issue by zXTury** [PluginsOCSInventory-NG/listprinters#2]
How can I reinstall a plugin? I delete it because i was playing arround.. now when i try to reinstall it shows the following: "This plugin has been already installed"

**Comment by vdeville** [comment]
Hello, @zxtury 
Remove plugin in database table `plugins`
Remove  /etc/ocsinventory-server/plugins/Listprinters.conf
Remove /etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/Listprinters/
Remove /usr/share/ocsinventory-reports/ocsreports/plugins/computer_detail/cd_listprinters

Thank
