### ISSUE TITLE
Network Printers are not listed

### ISSUE THREAD

**Issue by Scifire** [PluginsOCSInventory-NG/listprinters#3]
Hello,
we use Server OCS 2.3 on Ubuntu 16.04, Agent 2.3.0.0. on Win 10.
Installing the plugin was fine, also the vbs on the agent list me all printers including network printer when i start it local.

But in ocs on my machine under Miscellaneous i see only my  local printers (which are only software printer for pdf aso).
Agent log contains no error from this addon.
Server log also have no errors.

**Comment by gillesdubois** [comment]
@scifire91 Did you restart your apache server after installing the plugin ?

**Comment by Scifire** [comment]
Nope, i just restarted it and bumped into a new inventory.
unfortunately nothing changed

**Comment by gillesdubois** [comment]
Ok i will install the plugin and try to find what's going wrong.

**Comment by gillesdubois** [comment]
Hi,

Can you put your agent on debug = 1 and send me the log ?

Can you check if these files are on your server ? : 
 /etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/Listprinter/Map.pm 
 /etc/ocsinventory-server/plugins/Listprinter.conf

Thanks.

**Comment by Scifire** [comment]
Hey,

files you ask for are all present. 
i´ve shortend the log and deleted the ipdiscover results.
[log.txt](https://github.com/PluginsOCSInventory-NG/listprinters/files/692944/log.txt)

**Comment by gillesdubois** [comment]
Hi,

Your file produce an output ... weird the plugin seem to be correctly installed.
You should have infos showed in the webconsole.

Could you create a XML of your inventory and it to me ? ( use /XML argue on ocsinventory.exe to generate on xml )
Could you check the table "listprinters" in your ocs database ? If there any data stored in ?

Regards,
Gilles Dubois.

**Comment by Scifire** [comment]
databse is filled with local printers:
![grafik](https://cloud.githubusercontent.com/assets/17220258/21760970/45e4ce20-d650-11e6-948b-269e3caae60b.png)
can you give me an email or something then i send you the xml.

**Comment by gillesdubois** [comment]
Thx for your infos ... i don't need the XML anymore i got all the required informations to fix the bug :)
Thanks for your help, a fix will be available soon :)

**Comment by valencianista** [comment]
Hi
I have installed the plugin correctly.
My printers are installed on a network print server, and I install the printers on my computer.
And when running the agent, it does not detect networked printers, only local printers. Is there any solution?

**Comment by valencianista** [comment]
@scifire91 Did you find any solution to the problem?

**Comment by Scifire** [comment]
OCS 2.3 is already outdated so i close this.
