### ISSUE TITLE
Invalid Plugin on Version 2.3.1

### ISSUE THREAD

**Issue by LeFournG** [PluginsOCSInventory-NG/listprinters#5]
I'm trying to install the plugin on the ocs inventory web interface
and i got this problem : 

> ERROR: listprinters is an invalid plugin, check your sources.
Installation aborted ! 

I'm using version 2.3.1

**Comment by steph78630** [comment]
Hi,

you must download ZIP file, unzip and regenerate a new ZIP without the listprinters-master folder (keep only the content)

See : http://ask.ocsinventory-ng.org/8747/scheduledtasks-plugins-not-visible?show=8762#a8762

Regards, Stéphane
